In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import os
PROJECT_DIR = '/content/drive/MyDrive/ColabNotebooks/HDBprices'
RAW_DATA = PROJECT_DIR + '/data-raw/hdb_resale_raw_2017-2026.csv'
PROCESSED_DIR = PROJECT_DIR + '/data-processed'
os.makedirs(PROCESSED_DIR, exist_ok=True)

In [ ]:
print(os.path.exists(RAW_DATA))
df = pd.read_csv(RAW_DATA)

True

In [ ]:
df.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,232000.0
1,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,250000.0
2,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,262000.0
3,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,265000.0
4,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,265000.0

In [ ]:
print(df.shape)

(231771, 11)

In [ ]:
print(df.columns.tolist())

['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date', 'remaining_lease', 'resale_price']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231771 entries, 0 to 231770
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   month                231771 non-null  object
 1   town                 231771 non-null  object
 2   flat_type            231771 non-null  object
 3   block                231771 non-null  object
 4   street_name          231771 non-null  object
 5   storey_range         231771 non-null  object
 6   floor_area_sqm       231771 non-null  float64
 7   flat_model           231771 non-null  object
 8   lease_commence_date  231771 non-null  int64
 9   remaining_lease      231771 non-null  object
 10  resale_price         231771 non-null  float64
dtypes: float64(2), int64(1), object(8)
memory usage: 19.5+ MB

In [ ]:
df['month'] = pd.to_datetime(df['month'], format = '%Y-%m')
df['month'].head()

0   2017-01-01
1   2017-01-01
2   2017-01-01
3   2017-01-01
4   2017-01-01
Name: month, dtype: datetime64[ns]

In [ ]:
df_project = df[(df['month'].dt.year >= 2021) & (df['month'].dt.year <= 2025)].copy()
print(df_project.shape)
df_project.head()

(134479, 11)

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
87589,2021-01-01,ANG MO KIO,2 ROOM,170,ANG MO KIO AVE 4,01 TO 03,45.0,Improved,1986,64 years 01 month,211000.0
87590,2021-01-01,ANG MO KIO,2 ROOM,170,ANG MO KIO AVE 4,07 TO 09,45.0,Improved,1986,64 years 01 month,225000.0
87591,2021-01-01,ANG MO KIO,3 ROOM,331,ANG MO KIO AVE 1,04 TO 06,68.0,New Generation,1981,59 years,260000.0
87592,2021-01-01,ANG MO KIO,3 ROOM,534,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,58 years 02 months,265000.0
87593,2021-01-01,ANG MO KIO,3 ROOM,561,ANG MO KIO AVE 10,01 TO 03,68.0,New Generation,1980,58 years 01 month,265000.0

In [ ]:
df_project['year'] = df_project['month'].dt.year
df_project['lease_age'] = df_project['year'] - df_project['lease_commence_date']
df_project['price_per_sqm'] = (df_project['resale_price'] / df_project['floor_area_sqm'])
df_project[['month', 'year', 'lease_commence_date', 'lease_age', 'floor_area_sqm', 'resale_price', 'price_per_sqm']].head()

,month,year,lease_commence_date,lease_age,floor_area_sqm,resale_price,price_per_sqm
87589,2021-01-01,2021,1986,35,45.0,211000.0,4688.888889
87590,2021-01-01,2021,1986,35,45.0,225000.0,5000.000000
87591,2021-01-01,2021,1981,40,68.0,260000.0,3823.529412
87592,2021-01-01,2021,1980,41,68.0,265000.0,3897.058824
87593,2021-01-01,2021,1980,41,68.0,265000.0,3897.058824

In [ ]:
missing_value = df_project.isnull().sum()
print(missing_value)

month                  0
town                   0
flat_type              0
block                  0
street_name            0
storey_range           0
floor_area_sqm         0
flat_model             0
lease_commence_date    0
remaining_lease        0
resale_price           0
year                   0
lease_age              0
price_per_sqm          0
dtype: int64

In [ ]:
duplicate_count = df_project.duplicated().sum()
print('số dòng trùng lặp hoàn toàn:', duplicate_count)

số dòng trùng lặp hoàn toàn: 90

In [ ]:
df_project[['month', 'year', 'lease_commence_date', 'lease_age', 'floor_area_sqm', 'resale_price', 'price_per_sqm']].describe()

,month,year,lease_commence_date,lease_age,floor_area_sqm,resale_price,price_per_sqm
count,134479,134479.000000,134479.000000,134479.000000,134479.000000,1.344790e+05,134479.000000
mean,2023-05-27 10:21:46.856832768,2022.948765,1997.810863,25.137903,96.150652,5.778439e+05,6076.274966
min,2021-01-01 00:00:00,2021.000000,1966.000000,2.000000,31.000000,1.500000e+05,2238.805970
25%,2022-03-01 00:00:00,2022.000000,1985.000000,9.000000,78.000000,4.430000e+05,5044.247788
50%,2023-06-01 00:00:00,2023.000000,1998.000000,25.000000,93.000000,5.500000e+05,5738.636364
75%,2024-08-01 00:00:00,2024.000000,2014.000000,38.000000,112.000000,6.800000e+05,6687.500000
max,2025-12-01 00:00:00,2025.000000,2021.000000,59.000000,366.700000,1.658888e+06,16148.936170
std,NaN,1.419292,14.936296,14.963270,23.833570,1.865726e+05,1552.103631

In [ ]:
from numpy._core.defchararray import index
output_path = PROCESSED_DIR + '/hdb_resale_2021-2025.csv'
df_project.to_csv(
    output_path,
    index = False,
    encoding = 'utf-8-sig'
)
print("da luu tai:", output_path)

da luu tai: /content/drive/MyDrive/ColabNotebooks/HDBprices/data-processed/hdb_resale_2021-2025.csv

In [ ]:
import pandas as pd
import numpy as np
import re

DATA_PATH = '/content/drive/MyDrive/ColabNotebooks/HDBprices/data-processed/hdb_resale_2021-2025.csv'

df = pd.read_csv(DATA_PATH)

print(df.shape)
df.head()

(134479, 14)

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price,year,lease_age,price_per_sqm
0,2021-01-01,ANG MO KIO,2 ROOM,170,ANG MO KIO AVE 4,01 TO 03,45.0,Improved,1986,64 years 01 month,211000.0,2021,35,4688.888889
1,2021-01-01,ANG MO KIO,2 ROOM,170,ANG MO KIO AVE 4,07 TO 09,45.0,Improved,1986,64 years 01 month,225000.0,2021,35,5000.000000
2,2021-01-01,ANG MO KIO,3 ROOM,331,ANG MO KIO AVE 1,04 TO 06,68.0,New Generation,1981,59 years,260000.0,2021,40,3823.529412
3,2021-01-01,ANG MO KIO,3 ROOM,534,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,58 years 02 months,265000.0,2021,41,3897.058824
4,2021-01-01,ANG MO KIO,3 ROOM,561,ANG MO KIO AVE 10,01 TO 03,68.0,New Generation,1980,58 years 01 month,265000.0,2021,41,3897.058824

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134479 entries, 0 to 134478
Data columns (total 14 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   month                134479 non-null  object
 1   town                 134479 non-null  object
 2   flat_type            134479 non-null  object
 3   block                134479 non-null  object
 4   street_name          134479 non-null  object
 5   storey_range         134479 non-null  object
 6   floor_area_sqm       134479 non-null  float64
 7   flat_model           134479 non-null  object
 8   lease_commence_date  134479 non-null  int64
 9   remaining_lease      134479 non-null  object
 10  resale_price         134479 non-null  float64
 11  year                 134479 non-null  int64
 12  lease_age            134479 non-null  int64
 13  price_per_sqm        134479 non-null  float64
dtypes: float64(3), int64(3), object(8)
memory usage: 14.4+ MB

# Chuẩn hóa dữ liệu file csv mới
- vì model không chạy được với dữ liệu chữ, nên lấy trung bình tầng (strorey_mid)
- đổi dữ liệu về dạng tháng thập phân

In [ ]:
def get_storey_mid(storey_range):
    numbers = re.findall(r'\d+', str(storey_range))

    if len(numbers) == 2:
        low = int(numbers[0])
        high = int(numbers[1])
        return (low + high) / 2   #trung bình

    return np.nan  #nếu dữ liệu lạ trả về giá trị thiếu

df['storey_mid'] = df['storey_range'].apply(get_storey_mid)

df[['storey_range', 'storey_mid']].head(10)

  storey_range  storey_mid
0     01 TO 03         2.0
1     07 TO 09         8.0
2     04 TO 06         5.0
3     04 TO 06         5.0
4     01 TO 03         2.0
5     07 TO 09         8.0
6     04 TO 06         5.0
7     04 TO 06         5.0
8     07 TO 09         8.0
9     04 TO 06         5.0

In [ ]:
def lease_to_years(text):
  text = str(text)

  year = re.search(r'(\d+)\s*year', text)
  month = re.search(r'(\d+)\s*month', text)

  years = int(year.group(1)) if year else 0
  months = int(month.group(1)) if month else 0

  return years + months / 12

df['lease_years'] = df['remaining_lease'].apply(lease_to_years)

df[['remaining_lease', 'lease_years']].head(10)

      remaining_lease  lease_years
0   64 years 01 month    64.083333
1   64 years 01 month    64.083333
2            59 years    59.000000
3  58 years 02 months    58.166667
4   58 years 01 month    58.083333
5  64 years 02 months    64.166667
6  58 years 02 months    58.166667
7   59 years 01 month    59.083333
8            64 years    64.000000
9  54 years 04 months    54.333333

In [ ]:
df[['storey_range', 'storey_mid', 'remaining_lease', 'lease_years']].sample(10, random_state=42)

       storey_range  storey_mid     remaining_lease  lease_years
12387      07 TO 09         8.0  92 years 07 months    92.583333
44994      01 TO 03         2.0   89 years 01 month    89.083333
109583     10 TO 12        11.0  53 years 04 months    53.333333
68973      04 TO 06         5.0  64 years 06 months    64.500000
109061     10 TO 12        11.0  60 years 05 months    60.416667
75716      07 TO 09         8.0  65 years 04 months    65.333333
54363      01 TO 03         2.0   61 years 01 month    61.083333
35217      13 TO 15        14.0  94 years 03 months    94.250000
130291     01 TO 03         2.0  72 years 08 months    72.666667
122069     10 TO 12        11.0  68 years 10 months    68.833333

- cần dự đoán resale_price
- gộp danh sách số và chữ vào features

In [ ]:
target = 'resale_price'

numeric_features = ['floor_area_sqm', 'lease_age', 'lease_years', 'storey_mid', 'year']
categorical_features = ['town', 'flat_type', 'flat_model']

features = numeric_features + categorical_features

x = df[features]
y = df[target]

print("X shape:", x.shape)
print("Y shape:", y.shape)

x.head()

X shape: (134479, 8)
Y shape: (134479,)

,floor_area_sqm,lease_age,lease_years,storey_mid,year,town,flat_type,flat_model
0,45.0,35,64.083333,2.0,2021,ANG MO KIO,2 ROOM,Improved
1,45.0,35,64.083333,8.0,2021,ANG MO KIO,2 ROOM,Improved
2,68.0,40,59.000000,5.0,2021,ANG MO KIO,3 ROOM,New Generation
3,68.0,41,58.166667,5.0,2021,ANG MO KIO,3 ROOM,New Generation
4,68.0,41,58.083333,2.0,2021,ANG MO KIO,3 ROOM,New Generation

In [ ]:
#kiểm tra null
x.isnull().sum()

floor_area_sqm    0
lease_age         0
lease_years       0
storey_mid        0
year              0
town              0
flat_type         0
flat_model        0
dtype: int64

# Chia train/test

In [ ]:
from sklearn.model_selection import train_test_split

#20% test, 80% train, cố định chia dữ liệu 42
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2, random_state=42
)
print("Train size:", x_train.shape)
print("Test size:", x_test.shape)

Train size: (107583, 8)
Test size: (26896, 8)

# Chuẩn hóa cột số và mã hóa cột chữ
- StandardScaler_ số
- OneHotEnncoder_ chữ
- ColumTranformer _ gom việc

In [ ]:
from sklearn.compose import ColumnTransformer
# nhóm công cụ preprocessing biến đổi raw feture thành dạng phù hợp model
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

- các dữ liệu về chung đơn vị, ép nhỏ các trọng số w quá lớn_hàm phạt Ridge giải quyết
- 'SimpleImputer': phương trình hồi quy cần ma trận hoàn hảo -> fill các dòng dữ liệu bị thiếu = số trung vị/giá trị xuất hiện nhiều nhất

In [ ]:
numeric_trainsformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_trainsformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
])

# Train linear regression

In [ ]:
from sklearn.linear_model import LinearRegression

linear_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])
#học từ dữ liệu train
linear_model.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['floor_area_sqm',
                                                   'lease_age', 'lease_years',
                                                   'storey_mid', 'year']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['town', 'flat_type',
                                                   'flat_model'])])),
                ('regressor', LinearRegression())])

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_pred = linear_model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Linear Regression results")
print("MAE", mae)
print("MSE", mse)
print("R2", r2)    #dễ hiểu hơn vì cùng giá trị với giá nhà, càng gần 1 càng tốt

Linear Regression results
MAE 47796.40512680053
MSE 4032056309.0854974
R2 0.8827940022804437

# Train Ridge Regression
(so sánh thêm)

In [ ]:
from sklearn.linear_model import Ridge

ridge_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', Ridge(alpha=1.0))      #phat muc alpha, model cang lon thi a cang nho
])
ridge_model.fit(x_train, y_train)
ridge_pred = ridge_model.predict(x_test)

rid_mae = mean_absolute_error(y_test, ridge_pred)
rid_mse = mean_squared_error(y_test, ridge_pred)
rid_rmse = np.sqrt(mse)
rid_r2 = r2_score(y_test, ridge_pred)

print("Ridge Regression results")
print("MAE", mae)
print("MSE", mse)
print("R2", r2)

Ridge Regression results
MAE 47796.40512680053
MSE 4032056309.0854974
R2 0.8827940022804437

In [ ]:
results = pd.DataFrame({
    'model': ['Linear Regression', 'Ridge Regression'],
    'MAE': [mae, rid_mae],
    'RMSE': [rmse, rid_rmse],
    'R2': [r2, rid_r2]
})

results

               model           MAE          RMSE        R2
0  Linear Regression  47796.405127  63498.474856  0.882794
1   Ridge Regression  47790.639628  63498.474856  0.882795

Định nghĩa hàm Evaluate

In [ ]:
def evaluate_model(model, x_test, y_test, model_name):
    y_pred = model.predict(x_test)
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    print(f"--- {model_name} results ---")
    print("MAE:", mae)
    print("RMSE:", rmse)
    print("R2:", r2)

    return {'model': model_name, 'MAE': mae, 'RMSE': rmse, 'R2': r2}

Nhận xét: Linear Regression đạt kết quả tương đương Ridge trong baseline đầu tiên, cho thấy mô hình tuyến tính chưa bị ảnh hưởng nhiều bởi hệ số quá lớn ở bộ feature hiện tại.

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rf_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', RandomForestRegressor(
        n_estimators=100,
        max_depth=20,
        random_state=42,
        n_jobs=-1
    ))
])

rf_model.fit(x_train, y_train)

rf_result = evaluate_model(
    rf_model,
    x_test,
    y_test,
    'Random Forest'
)

rf_result

--- Random Forest results ---
MAE: 32180.94692703335
RMSE: 45408.79509520035
R2: 0.9400618679695925

{'model': 'Random Forest',
 'MAE': 32180.94692703335,
 'RMSE': np.float64(45408.79509520035),
 'R2': 0.9400618679695925}

Lưu model Random Forest

In [ ]:
import joblib

model_path = PROCESSED_DIR + '/rf_model_v1.pkl'

# 1. Lệnh LƯU model 
joblib.dump(rf_model, model_path)
print(f"Đã lưu model tại: {model_path}")

In [ ]:
rf_model = joblib.load(model_path)
print("Đã tải model thành công!")

So sánh hiệu suất các model

In [ ]:
# 1. lưu các thông số của 2 model trc
linear_res = evaluate_model(linear_model, x_test, y_test, 'Linear Regression')
ridge_res = evaluate_model(ridge_model, x_test, y_test, 'Ridge Regression')

# 2. Tạo bảng so sánh tổng hợp
comparison_df = pd.DataFrame([linear_res, ridge_res, rf_result])

print("\nBẢNG SO SÁNH HIỆU SUẤT 3 MÔ HÌNH:")
display(comparison_df.sort_values(by='R2', ascending=False))